name: Feature request
description: Suggest an idea for this project.
title: "[IDEA] "
labels: ["enhancement"]
assignees:
  - YerongAI
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us improve our software, we just need some information below.
  - type: input
    id: description
    attributes:
      label: Feature description
      description: What is this new feature about?
    validations:
      required: true
  - type: textarea
    id: how-to-work
    attributes:
      label: How does it work?
      description: If you know how to implement this feature, please let us know your ideas.
    validations:
      required: false